/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package resolverquerylogconfig

import (
	"context"

	svcapi "github.com/aws/aws-sdk-go/service/route53resolver"
	svcsdk "github.com/aws/aws-sdk-go/service/route53resolver"
	svcsdkapi "github.com/aws/aws-sdk-go/service/route53resolver/route53resolveriface"
	"github.com/google/go-cmp/cmp"
	"github.com/pkg/errors"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"

	svcapitypes "github.com/crossplane/provider-aws/apis/route53resolver/v1alpha1"
	awsclient "github.com/crossplane/provider-aws/pkg/clients"
)

const (
	errUnexpectedObject = "managed resource is not an ResolverQueryLogConfig resource"

	errCreateSession = "cannot create a new session"
	errCreate        = "cannot create ResolverQueryLogConfig in AWS"
	errUpdate        = "cannot update ResolverQueryLogConfig in AWS"
	errDescribe      = "failed to describe ResolverQueryLogConfig"
	errDelete        = "failed to delete ResolverQueryLogConfig"
)

type connector struct {
	kube client.Client
	opts []option
}

func (c *connector) Connect(ctx context.Context, mg cpresource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*svcapitypes.ResolverQueryLogConfig)
	if !ok {
		return nil, errors.New(errUnexpectedObject)
	}
	sess, err := awsclient.GetConfigV1(ctx, c.kube, mg, cr.Spec.ForProvider.Region)
	if err != nil {
		return nil, errors.Wrap(err, errCreateSession)
	}
	return newExternal(c.kube, svcapi.New(sess), c.opts), nil
}

func (e *external) Observe(ctx context.Context, mg cpresource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*svcapitypes.ResolverQueryLogConfig)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errUnexpectedObject)
	}
	if meta.GetExternalName(cr) == "" {
		return managed.ExternalObservation{
			ResourceExists: false,
		}, nil
	}
	input := GenerateGetResolverQueryLogConfigInput(cr)
	if err := e.preObserve(ctx, cr, input); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	resp, err := e.client.GetResolverQueryLogConfigWithContext(ctx, input)
	if err != nil {
		return managed.ExternalObservation{ResourceExists: false}, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	GenerateResolverQueryLogConfig(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)

	upToDate, err := e.isUpToDate(cr, resp)
	if err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
	}
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:          true,
		ResourceUpToDate:        upToDate,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
}

func (e *external) Create(ctx context.Context, mg cpresource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*svcapitypes.ResolverQueryLogConfig)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Creating())
	input := GenerateCreateResolverQueryLogConfigInput(cr)
	if err := e.preCreate(ctx, cr, input); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.CreateResolverQueryLogConfigWithContext(ctx, input)
	if err != nil {
		return managed.ExternalCreation{}, awsclient.Wrap(err, errCreate)
	}

	if resp.ResolverQueryLogConfig.Arn != nil {
		cr.Status.AtProvider.ARN = resp.ResolverQueryLogConfig.Arn
	} else {
		cr.Status.AtProvider.ARN = nil
	}
	if resp.ResolverQueryLogConfig.AssociationCount != nil {
		cr.Status.AtProvider.AssociationCount = resp.ResolverQueryLogConfig.AssociationCount
	} else {
		cr.Status.AtProvider.AssociationCount = nil
	}
	if resp.ResolverQueryLogConfig.CreationTime != nil {
		cr.Status.AtProvider.CreationTime = resp.ResolverQueryLogConfig.CreationTime
	} else {
		cr.Status.AtProvider.CreationTime = nil
	}
	if resp.ResolverQueryLogConfig.Id != nil {
		cr.Status.AtProvider.ID = resp.ResolverQueryLogConfig.Id
	} else {
		cr.Status.AtProvider.ID = nil
	}
	if resp.ResolverQueryLogConfig.OwnerId != nil {
		cr.Status.AtProvider.OwnerID = resp.ResolverQueryLogConfig.OwnerId
	} else {
		cr.Status.AtProvider.OwnerID = nil
	}
	if resp.ResolverQueryLogConfig.ShareStatus != nil {
		cr.Status.AtProvider.ShareStatus = resp.ResolverQueryLogConfig.ShareStatus
	} else {
		cr.Status.AtProvider.ShareStatus = nil
	}
	if resp.ResolverQueryLogConfig.Status != nil {
		cr.Status.AtProvider.Status = resp.ResolverQueryLogConfig.Status
	} else {
		cr.Status.AtProvider.Status = nil
	}

	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, mg cpresource.Managed) (managed.ExternalUpdate, error) {
	return e.update(ctx, mg)

}

func (e *external) Delete(ctx context.Context, mg cpresource.Managed) error {
	cr, ok := mg.(*svcapitypes.ResolverQueryLogConfig)
	if !ok {
		return errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Deleting())
	input := GenerateDeleteResolverQueryLogConfigInput(cr)
	ignore, err := e.preDelete(ctx, cr, input)
	if err != nil {
		return errors.Wrap(err, "pre-delete failed")
	}
	if ignore {
		return nil
	}
	resp, err := e.client.DeleteResolverQueryLogConfigWithContext(ctx, input)
	return e.postDelete(ctx, cr, resp, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDelete))
}

type option func(*external)

func newExternal(kube client.Client, client svcsdkapi.Route53ResolverAPI, opts []option) *external {
	e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		preDelete:      nopPreDelete,
		postDelete:     nopPostDelete,
		update:         nopUpdate,
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube           client.Client
	client         svcsdkapi.Route53ResolverAPI
	preObserve     func(context.Context, *svcapitypes.ResolverQueryLogConfig, *svcsdk.GetResolverQueryLogConfigInput) error
	postObserve    func(context.Context, *svcapitypes.ResolverQueryLogConfig, *svcsdk.GetResolverQueryLogConfigOutput, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	lateInitialize func(*svcapitypes.ResolverQueryLogConfigParameters, *svcsdk.GetResolverQueryLogConfigOutput) error
	isUpToDate     func(*svcapitypes.ResolverQueryLogConfig, *svcsdk.GetResolverQueryLogConfigOutput) (bool, error)
	preCreate      func(context.Context, *svcapitypes.ResolverQueryLogConfig, *svcsdk.CreateResolverQueryLogConfigInput) error
	postCreate     func(context.Context, *svcapitypes.ResolverQueryLogConfig, *svcsdk.CreateResolverQueryLogConfigOutput, managed.ExternalCreation, error) (managed.ExternalCreation, error)
	preDelete      func(context.Context, *svcapitypes.ResolverQueryLogConfig, *svcsdk.DeleteResolverQueryLogConfigInput) (bool, error)
	postDelete     func(context.Context, *svcapitypes.ResolverQueryLogConfig, *svcsdk.DeleteResolverQueryLogConfigOutput, error) error
	update         func(context.Context, cpresource.Managed) (managed.ExternalUpdate, error)
}

func nopPreObserve(context.Context, *svcapitypes.ResolverQueryLogConfig, *svcsdk.GetResolverQueryLogConfigInput) error {
	return nil
}

func nopPostObserve(_ context.Context, _ *svcapitypes.ResolverQueryLogConfig, _ *svcsdk.GetResolverQueryLogConfigOutput, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	return obs, err
}
func nopLateInitialize(*svcapitypes.ResolverQueryLogConfigParameters, *svcsdk.GetResolverQueryLogConfigOutput) error {
	return nil
}
func alwaysUpToDate(*svcapitypes.ResolverQueryLogConfig, *svcsdk.GetResolverQueryLogConfigOutput) (bool, error) {
	return true, nil
}

func nopPreCreate(context.Context, *svcapitypes.ResolverQueryLogConfig, *svcsdk.CreateResolverQueryLogConfigInput) error {
	return nil
}
func nopPostCreate(_ context.Context, _ *svcapitypes.ResolverQueryLogConfig, _ *svcsdk.CreateResolverQueryLogConfigOutput, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	return cre, err
}
func nopPreDelete(context.Context, *svcapitypes.ResolverQueryLogConfig, *svcsdk.DeleteResolverQueryLogConfigInput) (bool, error) {
	return false, nil
}
func nopPostDelete(_ context.Context, _ *svcapitypes.ResolverQueryLogConfig, _ *svcsdk.DeleteResolverQueryLogConfigOutput, err error) error {
	return err
}
func nopUpdate(context.Context, cpresource.Managed) (managed.ExternalUpdate, error) {
	return managed.ExternalUpdate{}, nil
}
