/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package resolverquerylogconfig

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/route53resolver"

	svcapitypes "github.com/crossplane/provider-aws/apis/route53resolver/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateGetResolverQueryLogConfigInput returns input for read
// operation.
func GenerateGetResolverQueryLogConfigInput(cr *svcapitypes.ResolverQueryLogConfig) *svcsdk.GetResolverQueryLogConfigInput {
	res := &svcsdk.GetResolverQueryLogConfigInput{}

	return res
}

// GenerateResolverQueryLogConfig returns the current state in the form of *svcapitypes.ResolverQueryLogConfig.
func GenerateResolverQueryLogConfig(resp *svcsdk.GetResolverQueryLogConfigOutput) *svcapitypes.ResolverQueryLogConfig {
	cr := &svcapitypes.ResolverQueryLogConfig{}

	if resp.ResolverQueryLogConfig.Arn != nil {
		cr.Status.AtProvider.ARN = resp.ResolverQueryLogConfig.Arn
	} else {
		cr.Status.AtProvider.ARN = nil
	}
	if resp.ResolverQueryLogConfig.AssociationCount != nil {
		cr.Status.AtProvider.AssociationCount = resp.ResolverQueryLogConfig.AssociationCount
	} else {
		cr.Status.AtProvider.AssociationCount = nil
	}
	if resp.ResolverQueryLogConfig.CreationTime != nil {
		cr.Status.AtProvider.CreationTime = resp.ResolverQueryLogConfig.CreationTime
	} else {
		cr.Status.AtProvider.CreationTime = nil
	}
	if resp.ResolverQueryLogConfig.Id != nil {
		cr.Status.AtProvider.ID = resp.ResolverQueryLogConfig.Id
	} else {
		cr.Status.AtProvider.ID = nil
	}
	if resp.ResolverQueryLogConfig.OwnerId != nil {
		cr.Status.AtProvider.OwnerID = resp.ResolverQueryLogConfig.OwnerId
	} else {
		cr.Status.AtProvider.OwnerID = nil
	}
	if resp.ResolverQueryLogConfig.ShareStatus != nil {
		cr.Status.AtProvider.ShareStatus = resp.ResolverQueryLogConfig.ShareStatus
	} else {
		cr.Status.AtProvider.ShareStatus = nil
	}
	if resp.ResolverQueryLogConfig.Status != nil {
		cr.Status.AtProvider.Status = resp.ResolverQueryLogConfig.Status
	} else {
		cr.Status.AtProvider.Status = nil
	}

	return cr
}

// GenerateCreateResolverQueryLogConfigInput returns a create input.
func GenerateCreateResolverQueryLogConfigInput(cr *svcapitypes.ResolverQueryLogConfig) *svcsdk.CreateResolverQueryLogConfigInput {
	res := &svcsdk.CreateResolverQueryLogConfigInput{}

	if cr.Spec.ForProvider.CreatorRequestID != nil {
		res.SetCreatorRequestId(*cr.Spec.ForProvider.CreatorRequestID)
	}
	if cr.Spec.ForProvider.DestinationARN != nil {
		res.SetDestinationArn(*cr.Spec.ForProvider.DestinationARN)
	}
	if cr.Spec.ForProvider.Name != nil {
		res.SetName(*cr.Spec.ForProvider.Name)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f3 := []*svcsdk.Tag{}
		for _, f3iter := range cr.Spec.ForProvider.Tags {
			f3elem := &svcsdk.Tag{}
			if f3iter.Key != nil {
				f3elem.SetKey(*f3iter.Key)
			}
			if f3iter.Value != nil {
				f3elem.SetValue(*f3iter.Value)
			}
			f3 = append(f3, f3elem)
		}
		res.SetTags(f3)
	}

	return res
}

// GenerateDeleteResolverQueryLogConfigInput returns a deletion input.
func GenerateDeleteResolverQueryLogConfigInput(cr *svcapitypes.ResolverQueryLogConfig) *svcsdk.DeleteResolverQueryLogConfigInput {
	res := &svcsdk.DeleteResolverQueryLogConfigInput{}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
